version: 2.6.{build}

image: 
- Visual Studio 2019
- Ubuntu2004
- macos

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- ps: >-
    if(!$isLinux -AND !$isWindows)
    {
        # Install .NET 5.0 on macOS
        curl -fsSL https://download.visualstudio.microsoft.com/download/pr/0871336f-9a83-4ce4-80ca-625d03003369/2eb78456e0b106e9515dc03898d3867a/dotnet-sdk-5.0.100-osx-x64.tar.gz -o dotnet-sdk.tar.gz
        sudo tar zxf dotnet-sdk.tar.gz -C /usr/local/share/dotnet
    }

build_script:
- ps: >-
    dotnet --info
    
    if($isWindows)
    {
        # Publish and package Self Contained Executables        
        dotnet publish SerialDisk/Serialdisk.csproj -r win-x64 -c Release --self-contained true --output ./bin/Release/SCE/win-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true
        dotnet publish SerialDisk/Serialdisk.csproj -r win-x86 -c Release --self-contained true --output ./bin/Release/SCE/win-x86 /p:PublishTrimmed=true /p:PublishSingleFile=true
        
        # Publish and package Framework Dependant Executables        
        dotnet publish SerialDisk/Serialdisk.csproj -r win-x64 -c Release --self-contained false --output ./bin/Release/FDE/win-x64
        dotnet publish SerialDisk/Serialdisk.csproj -r win-x86 -c Release --self-contained false --output ./bin/Release/FDE/win-x86
    }

    elseif($isLinux)
    {
        # Publish and package Self Contained Executables        
        dotnet publish ./SerialDisk/SerialDisk.csproj -r linux-x64 -c Release --self-contained true --output ./bin/Release/SCE/serialdisk-linux-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true
        dotnet publish SerialDisk/SerialDisk.csproj -r linux-arm64 -c Release --self-contained true --output ./bin/Release/SCE/serialdisk-linux-arm64 /p:PublishTrimmed=true /p:PublishSingleFile=true
        dotnet publish SerialDisk/SerialDisk.csproj -r linux-arm -c Release --self-contained true --output ./bin/Release/SCE/serialdisk-linux-arm32 /p:PublishTrimmed=true /p:PublishSingleFile=true

        # Publish and package Framework Dependant Executables
        dotnet publish SerialDisk/SerialDisk.csproj -r linux-x64 -c Release --self-contained false --output ./bin/Release/FDE/serialdisk-linux-x64
        dotnet publish SerialDisk/SerialDisk.csproj -r linux-arm64 -c Release --self-contained false --output ./bin/Release/FDE/serialdisk-linux-arm64
        dotnet publish SerialDisk/SerialDisk.csproj -r linux-arm -c Release --self-contained false --output ./bin/Release/FDE/serialdisk-linux-arm32
    }
    
    else
    {    
        # Publish and package Self Contained Executables        
        dotnet publish SerialDisk/SerialDisk.csproj -r osx-x64 -c Release --self-contained true --output ./bin/Release/SCE/serialdisk-macos-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true

        # Publish and package Framework Dependant Executables
        dotnet publish SerialDisk/SerialDisk.csproj -r osx-x64 -c Release --self-contained false --output ./bin/Release/FDE/serialdisk-macos-x64
    }

on_success:
- ps: >-
    $versionNo = "2.6"
    
    if($isWindows)
    {
        7z a -mx=9 serialdisk_$($versionNo)_sce_win-x64.zip ./bin/Release/SCE/win-x64/*
        appveyor PushArtifact serialdisk_$($versionNo)_sce_win-x64.zip

        7z a -mx=9 serialdisk_$($versionNo)_sce_win-x86.zip ./bin/Release/SCE/win-x86/*
        appveyor PushArtifact serialdisk_$($versionNo)_sce_win-x86.zip

        7z a -mx=9 serialdisk_$($versionNo)_fde_win-x64.zip ./bin/Release/FDE/win-x64/*
        appveyor PushArtifact serialdisk_$($versionNo)_fde_win-x64.zip

        7z a -mx=9 serialdisk_$($versionNo)_fde_win-x86.zip ./bin/Release/FDE/win-x86/*
        appveyor PushArtifact serialdisk_$($versionNo)_fde_win-x86.zip
    }
    
    elseif($isLinux)
    {
        tar -czf serialdisk_$($versionNo)_sce_linux-x64.tar.gz -C ./bin/Release/SCE serialdisk-linux-x64
        appveyor PushArtifact serialdisk_$($versionNo)_sce_linux-x64.tar.gz

        tar -czf serialdisk_$($versionNo)_sce_linux-arm64.tar.gz -C ./bin/Release/SCE serialdisk-linux-arm64
        appveyor PushArtifact serialdisk_$($versionNo)_sce_linux-arm64.tar.gz

        tar -czf serialdisk_$($versionNo)_sce_linux-arm32.tar.gz -C ./bin/Release/SCE serialdisk-linux-arm32
        appveyor PushArtifact serialdisk_$($versionNo)_sce_linux-arm32.tar.gz

        tar -czf serialdisk_$($versionNo)_fde_linux-x64.tar.gz -C ./bin/Release/FDE serialdisk-linux-x64
        appveyor PushArtifact serialdisk_$($versionNo)_fde_linux-x64.tar.gz

        tar -czf serialdisk_$($versionNo)_fde_linux-arm64.tar.gz -C ./bin/Release/FDE serialdisk-linux-arm64
        appveyor PushArtifact serialdisk_$($versionNo)_fde_linux-arm64.tar.gz

        tar -czf serialdisk_$($versionNo)_fde_linux-arm32.tar.gz -C ./bin/Release/FDE serialdisk-linux-arm32
        appveyor PushArtifact serialdisk_$($versionNo)_fde_linux-arm32.tar.gz
    }
    
    else
    {
        tar -czf serialdisk_$($versionNo)_sce_macos-x64.tar.gz -C ./bin/Release/SCE serialdisk-macos-x64
        appveyor PushArtifact serialdisk_$($versionNo)_sce_macos-x64.tar.gz
        
        tar -czf serialdisk_$($versionNo)_fde_macos-x64.tar.gz -C ./bin/Release/FDE serialdisk-macos-x64
        appveyor PushArtifact serialdisk_$($versionNo)_fde_macos-x64.tar.gz        
    }

test_script:
- ps: >-
    dotnet clean
    
    dotnet test --test-adapter-path:. --logger:Appveyor -nodereuse:false

deploy: off
